Repository instaclustr/cassandra-operator, pull requests merged in 2019-09, with the labels that each got.

#293 Docs simplification
  README.md
  doc/op_guide.md
  doc/providers/aks.md
  doc/providers/gke.md
  doc/providers/local.md
  doc/run_cluster.md
Labels: documentation

#288 CircleCI updates for go switch
  .circleci/config.yml
  buildenv/build-all
  buildenv/release-all
Labels: build, circleci

#292 Parametrize build scripts
  .gitignore
  docker/base-openjre/Dockerfile
  docker/base-openjre/Makefile
  docker/cassandra-operator/Dockerfile
  docker/cassandra-operator/Makefile
  docker/cassandra/Dockerfile
  docker/cassandra/Makefile
  docker/cassandra/install-cassandra
Labels: build
